import Head from "next/head";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Column from "./components/column";
import { useEffect, useState } from "react";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

interface WeatherData {
  date: string;
  weatherCode: number;
  temperature2mMax: number;
  temperature2mMin: number;
  estimatedEnergy: number;
}





export async function getServerSideProps() {
  let lat = 30;
  let lon = 20;
  const res = await fetch(`https://backend-weatherapp-2oet.onrender.com/endpoint1?lat=${lat}&lon=${lon}`);
  const data: WeatherData[] = await res.json();

  return {
    props: {
      weatherData: data,
    },
  };
}

interface HomeProps {
  weatherData: WeatherData[];
}

export default function Home({ weatherData }: HomeProps): JSX.Element {
  const [location, setLocation] = useState<{ lat: number; lon: number } | null>(null);


  // Pobieranie coordow uzytkownika 
  useEffect(() => {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition((position) => {
        setLocation({ 
          lat: position.coords.latitude,
           lon: position.coords.longitude
           });
        console.log(position.coords);
      });
    }
  }, []);

  // MIEJSCE NA DRUGI HOOK AKTUALIZUJACY ZMIANY WYWOLANE PRZEZ PIERWSZY 

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}>
        <main className={styles.main}>
          <div className={styles.columnsContainer}>
            {weatherData.map((data) => (
              <Column
                key={data.date}
                date={data.date}
                weatherCode={data.weatherCode}
                temperature2mMax={data.temperature2mMax}
                temperature2mMin={data.temperature2mMin}
                estimatedEnergy={data.estimatedEnergy}
              />
            ))}
          </div>
        </main>
      </div>
    </>
  );
}
